### PR TITLE
feat(faucet): bind tokens to address

### LINKED ISSUE #61: After first call to faucet with valid token, only the same account should be able to use that token

### PR DESCRIPTION
**Pull request by tbruyelle**
Closes #61

Returns an error if a token is already bound to an address. Works only in memory, bound tokens are reset on restart.

This is the dumbest possible change to avoid new bugs since there's no tests.

### CODE REVIEW

**Comment by tbruyelle** [comment]
Converted to draft because I've just seen that comment ^^ https://github.com/gnolang/gnochess/issues/61#issuecomment-1731518667

Need to save data on disk.

**Comment by zivkovicmilos** [comment]
@tbruyelle 
Working with @albttx to get this supported on the sign up form so these things are "in sync"

**Comment by tbruyelle** [comment]
@thehowl @zivkovicmilos Oh damned so these tokens in the faucet binary flags aren't supposed to stay, so we need a shared storage with the signup and the faucet. We'll work on that with @albttx.

**Comment by albttx** [comment]
close for #74

**Pull request closed without merging**
