### PR TITLE
fix: gameover - resign - draw engine

### PR DESCRIPTION
**Pull request by alexiscolin**
For #103 and #104 and #105 and #111

### CODE REVIEW

**Comment by thehowl** [comment]
Things I noted in my tests:

- If a player resigns, they're kicked out to the main page. I think we should still show the endgame screen, no?
- Tried to play a [scholar's mate](https://lichess.org/study/lALNSfhG/0WqP29x3). White gets this error in the console:
image

**Comment by alexiscolin** [comment]
@thehowl 
- The user leave the page when he resigns. It's not a bug but may not be the normal behavior? We will be able to change it later.
- the second one is weird since the HTML is in the place and the same as the "resign draw etc"...

**Comment by ajnavarro** [comment]
Found another error:

```
`Error: internal error encountered
    ee errors.js:23
    ee errors.js:33
    constructRequestError errors.utility.js:17
    JSONRPCProvider jsonrpc.js:258
    Be jsonrpc.js:33
    ye jsonrpc.js:14
    ye jsonrpc.js:5
    promise callback*Ee jsonrpc.js:7
    7 jsonrpc.js:8
    7 jsonrpc.js:4
    broadcastTxCommit jsonrpc.js:238
    JSONRPCProvider jsonrpc.js:206
    Be jsonrpc.js:33
    ye jsonrpc.js:14
    7 jsonrpc.js:8
    7 jsonrpc.js:4
    sendTransaction jsonrpc.js:198
    Wallet wallet.js:270
    Be wallet.js:44
    ye wallet.js:25
    3 wallet.js:19
    3 wallet.js:15
    sendTransaction wallet.js:262
    GnoWallet wallet.js:163
    Be wallet.js:48
    ye wallet.js:29
    ye wallet.js:20
    promise callback*Ee wallet.js:22
    ye wallet.js:20
    promise callback*Ee wallet.js:22
    __awaiter wallet.js:23
    __awaiter wallet.js:19
    callMethod wallet.js:126
    callMethod actions.ts:172
    joinLobby actions.ts:242
    _clickOnCtrl1 gameoptions.ts:275
    value sevejs.umd.js:1
    init gameoptions.ts:120
    value sevejs.umd.js:1
    value sevejs.umd.js:1
    value sevejs.umd.js:1
    value sevejs.umd.js:1
    value sevejs.umd.js:1
    value sevejs.umd.js:1
    value sevejs.umd.js:1
    afterEnter router.ts:98
    de barba.mjs:1
    N barba.mjs:1
    st barba.mjs:1
    de barba.mjs:1
    N barba.mjs:1
    Be barba.mjs:1
    promise callback*RA</ie.do/X< barba.mjs:1
    do barba.mjs:1
gameoptions.ts:323:18
``

**Comment by ajnavarro** [comment]
Screenshot from 2023-09-25 10-59-40

Blacks resigning worked for me.

**Comment by alexiscolin** [comment]
@tbruyelle @zivkovicmilos Should be good to go now

**Review by zivkovicmilos — APPROVED** [review]

**Pull request merged**
