### PR TITLE
fix: Add Wallet & Balance checks to gameoptions

### PR DESCRIPTION
**Pull request by clockworkgr**
fixes https://github.com/gnolang/gnochess/issues/142

### CODE REVIEW

**Review by zivkovicmilos — APPROVED** [review]

**Comment by alexiscolin** [comment]
@clockworkgr @zivkovicmilos I've added some commits, the flow should be better like that but it would need a promise in the `hasWallet()` action somewhere as it's `false` when you reload the /play page

**Comment by clockworkgr** [comment]
> @clockworkgr @zivkovicmilos I've added some commits, the flow should be better like that but it would need a promise in the `hasWallet()` action somewhere as it's `false` when you reload the /play page

hmmm...that's weird...there's nothing async about hasWallet. it simply checks if this.wallet in actions is initialized.

In order to call actions.hasWallet() gameoptions awaits Actions.getInstance which in turn awaits initialize() which should pull the mnemonic and init the wallet :/

I dont see a mistake anywhere tbh so not sure how this is happening

**Comment by alexiscolin** [comment]
Yes I don't understand it either. But with a timeout it works 

```js
actions.hasWallet() // -> false
setTimout(() => actions.hasWallet(), 1000) // -> true
```

**Comment by clockworkgr** [comment]
> Yes I don't understand it either. But with a timeout it works 
> 
> ```js
> actions.hasWallet() // -> false
> setTimout(() => actions.hasWallet(), 500) // -> true
> ```
> 

Ok... I'll debug...something with the actions initialization I guess

**Comment by clockworkgr** [comment]
@alexiscolin bug was https://github.com/gnolang/gnochess/pull/179

**Pull request merged**
